# Generated by Django 4.0.5 on 2022-07-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offliner', '0002_page_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
    ]
