# Generated by Django 4.0.5 on 2022-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offliner', '0006_remove_paper_user_paper_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
