# Generated by Django 4.0.5 on 2022-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offliner', '0007_paper_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
